version: '2'

services:
  db:
    image: couchdb:1.6 
    container_name: local.ikp
    volumes:
      - ./db/data:/usr/local/var/lib/couchdb
    logging:
      options:
        max-size: "100m"
        max-file: "1"
  app:
    build:
      context: ./
    image: ikakpalka:0.1
    container_name: local.ikp.app
    command: python -m main
    volumes:
      - ./src/:/app
    ports:
      - "10000:10000"
  bal:
    build:
      context: ./
    image: ikakpalka:0.1
    container_name: local.ikp.bal
    command: python -m main
    volumes:
      - ./src/:/app
    ports:
      - "10000:10001"
  nginx:
    image: nginx:1.10
    container_name: local.ikp.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

networks:
  default:
    external:
      name: ikakpalka

